### ISSUE TITLE
Player standing tile awareness feature

### ISSUE THREAD

**Issue by hoonsubin** [TeamSTEP/witch-one-homepage#6]
## Required Tasks:
- [ ] allow the game to know what tile the current player is standing on (by metadata)
- [x] ~allow the game to know the height of the tile that the current player is standing on (by sorting layer)~
- [x] ~prevent players from catching other players with a different height level (no "I have the high ground" situation)~
- [ ] optimize the standing tile search to reduce background processing
- [ ] add different sound effects for different surface types
- [ ] add different sound wave travel distance for different surface types
- [ ] add different footprints on different surface types (different sprite)

## Description:

Surface types have two major functionalities:
1. does the current surface leave a footprint?
2. which sound effect and the size of the volume (the wave effect will play based on the volume)

Different tilemap frameworks such as Unity 2D Tilemap or Super Tilemap Editor has their own way of handling tile position in a map and embedding metadata. So it might be better for us to abstract the tile detection feature into an interface and execute the methods from a component within the tilemap game object.

**Note:** this task may need to be split in to two

## Difficulty

8/10

## Estimated Implementation Time

- Optimistic - {how long this will take to finish all the subtasks at the very least}
- Normal - {how long this will take to finish all the subtasks on average work time}
- Pessimistic - {how long this will take to finish all the subtasks at most}

## Work Start Date

{when will the implementation will start}

**Comment by ngmgit** [comment]
I was able to get the current standing surface based on the current tile the player i on based on position. Gave it a lot of though if I should go with tilmap name or just the tile name. And considered to got with tile.

The solutions makes sure that only the tilemaps in the TileContainer with tag equals "Tilemap" are considered and a desc sort based on the "Order in layer" param is applied.  Will be submitting PR.

**Comment by hoonsubin** [comment]
great. After merging this PR, we can think about making an actual stage with different environments and sound effects.
